"""Minimal client for the OpenAI Responses API."""

from __future__ import annotations

import json
from dataclasses import dataclass
from json import JSONDecodeError
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from app.core.config import get_settings


OPENAI_RESPONSES_URL = (
    "https://api.openai.com/v1/responses"
)


class OpenAIConfigurationError(RuntimeError):
    """Raised when OpenAI configuration is incomplete."""


class OpenAIResponseError(RuntimeError):
    """Raised when OpenAI text generation fails."""


@dataclass(frozen=True, slots=True)
class GeneratedText:
    """Text generated by one model response."""

    text: str
    model: str


def _extract_output_text(
    payload: dict[str, Any],
) -> str:
    """Extract assistant text from a Responses API payload."""

    direct_output_text = payload.get(
        "output_text"
    )

    if isinstance(
        direct_output_text,
        str,
    ):
        normalized_text = direct_output_text.strip()

        if normalized_text:
            return normalized_text

    output_items = payload.get(
        "output",
        [],
    )

    if not isinstance(
        output_items,
        list,
    ):
        raise OpenAIResponseError(
            "OpenAI returned an invalid output structure."
        )

    text_parts: list[str] = []

    for output_item in output_items:
        if not isinstance(
            output_item,
            dict,
        ):
            continue

        content_items = output_item.get(
            "content",
            [],
        )

        if not isinstance(
            content_items,
            list,
        ):
            continue

        for content_item in content_items:
            if not isinstance(
                content_item,
                dict,
            ):
                continue

            if content_item.get("type") != "output_text":
                continue

            text = content_item.get(
                "text"
            )

            if isinstance(
                text,
                str,
            ) and text.strip():
                text_parts.append(
                    text.strip()
                )

    generated_text = "\n".join(
        text_parts
    ).strip()

    if not generated_text:
        raise OpenAIResponseError(
            "OpenAI returned no generated text."
        )

    return generated_text


class OpenAIResponsesClient:
    """Synchronous OpenAI Responses API client."""

    def __init__(
        self,
        api_key: str,
        model: str,
        timeout_seconds: float = 60.0,
    ) -> None:
        normalized_api_key = api_key.strip()
        normalized_model = model.strip()

        if not normalized_api_key:
            raise OpenAIConfigurationError(
                "OPENAI_API_KEY is not configured."
            )

        if not normalized_model:
            raise OpenAIConfigurationError(
                "OPENAI_MODEL is not configured."
            )

        if timeout_seconds <= 0:
            raise OpenAIConfigurationError(
                "OPENAI_TIMEOUT_SECONDS must be positive."
            )

        self.api_key = normalized_api_key
        self.model = normalized_model
        self.timeout_seconds = timeout_seconds

    def generate(
        self,
        instructions: str,
        input_text: str,
    ) -> GeneratedText:
        """Generate one text response."""

        request_body = {
            "model": self.model,
            "instructions": instructions,
            "input": input_text,
            "store": False,
        }

        encoded_body = json.dumps(
            request_body
        ).encode(
            "utf-8"
        )

        request = Request(
            url=OPENAI_RESPONSES_URL,
            data=encoded_body,
            method="POST",
            headers={
                "Authorization": (
                    f"Bearer {self.api_key}"
                ),
                "Content-Type": "application/json",
            },
        )

        try:
            with urlopen(
                request,
                timeout=self.timeout_seconds,
            ) as response:
                raw_response = response.read()

        except HTTPError as error:
            error_message = (
                f"OpenAI returned HTTP {error.code}."
            )

            try:
                error_payload = json.loads(
                    error.read().decode(
                        "utf-8"
                    )
                )

                api_error = error_payload.get(
                    "error",
                    {},
                )

                if isinstance(
                    api_error,
                    dict,
                ):
                    api_message = api_error.get(
                        "message"
                    )

                    if isinstance(
                        api_message,
                        str,
                    ) and api_message.strip():
                        error_message = api_message.strip()

            except (
                JSONDecodeError,
                UnicodeDecodeError,
            ):
                pass

            raise OpenAIResponseError(
                error_message
            ) from error

        except (
            URLError,
            TimeoutError,
            OSError,
        ) as error:
            raise OpenAIResponseError(
                "OpenAI could not be reached."
            ) from error

        try:
            payload = json.loads(
                raw_response.decode(
                    "utf-8"
                )
            )

        except (
            JSONDecodeError,
            UnicodeDecodeError,
        ) as error:
            raise OpenAIResponseError(
                "OpenAI returned invalid JSON."
            ) from error

        if not isinstance(
            payload,
            dict,
        ):
            raise OpenAIResponseError(
                "OpenAI returned an invalid response."
            )

        response_model = payload.get(
            "model",
            self.model,
        )

        if not isinstance(
            response_model,
            str,
        ):
            response_model = self.model

        return GeneratedText(
            text=_extract_output_text(
                payload
            ),
            model=response_model,
        )


def get_openai_responses_client() -> OpenAIResponsesClient:
    """Build the configured OpenAI client."""

    settings = get_settings()

    if not settings.openai_api_key:
        raise OpenAIConfigurationError(
            "OPENAI_API_KEY is not configured."
        )

    return OpenAIResponsesClient(
        api_key=settings.openai_api_key,
        model=settings.openai_model,
        timeout_seconds=(
            settings.openai_timeout_seconds
        ),
    )