"""Minimal client for the OpenAI Responses API."""

from __future__ import annotations

import json
from dataclasses import dataclass
from json import JSONDecodeError
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from app.core.config import get_settings


OPENAI_RESPONSES_URL = (
    "https://api.openai.com/v1/responses"
)


class OpenAIConfigurationError(RuntimeError):
    """Raised when OpenAI configuration is incomplete."""


class OpenAIResponseError(RuntimeError):
    """
    Raised when OpenAI text generation fails.

    `retryable` distinguishes a transient failure (timeout, connection
    error, HTTP 429/500/502/503/504) - safe for a caller to retry once -
    from a definitive one (HTTP 400/401/403, or any failure that happens
    only after a response was already successfully received, such as
    invalid JSON or an incomplete-status response) - never retried,
    since retrying would not change the outcome.
    """

    def __init__(
        self,
        message: str,
        *,
        retryable: bool = False,
        status_code: int | None = None,
    ) -> None:
        super().__init__(message)
        self.retryable = retryable
        self.status_code = status_code


@dataclass(frozen=True, slots=True)
class GeneratedText:
    """Text generated by one model response."""

    text: str
    model: str


def _extract_output_text(
    payload: dict[str, Any],
) -> str:
    """Extract assistant text from a Responses API payload."""

    direct_output_text = payload.get(
        "output_text"
    )

    if isinstance(
        direct_output_text,
        str,
    ):
        normalized_text = direct_output_text.strip()

        if normalized_text:
            return normalized_text

    output_items = payload.get(
        "output",
        [],
    )

    if not isinstance(
        output_items,
        list,
    ):
        raise OpenAIResponseError(
            "OpenAI returned an invalid output structure."
        )

    text_parts: list[str] = []

    for output_item in output_items:
        if not isinstance(
            output_item,
            dict,
        ):
            continue

        content_items = output_item.get(
            "content",
            [],
        )

        if not isinstance(
            content_items,
            list,
        ):
            continue

        for content_item in content_items:
            if not isinstance(
                content_item,
                dict,
            ):
                continue

            if content_item.get("type") != "output_text":
                continue

            text = content_item.get(
                "text"
            )

            if isinstance(
                text,
                str,
            ) and text.strip():
                text_parts.append(
                    text.strip()
                )

    generated_text = "\n".join(
        text_parts
    ).strip()

    if not generated_text:
        raise OpenAIResponseError(
            "OpenAI returned no generated text."
        )

    return generated_text


class OpenAIResponsesClient:
    """Synchronous OpenAI Responses API client."""

    def __init__(
        self,
        api_key: str,
        model: str,
        timeout_seconds: float = 60.0,
        reasoning_effort: str | None = None,
        max_output_tokens: int | None = None,
    ) -> None:
        normalized_api_key = api_key.strip()
        normalized_model = model.strip()

        if not normalized_api_key:
            raise OpenAIConfigurationError(
                "OPENAI_API_KEY is not configured."
            )

        if not normalized_model:
            raise OpenAIConfigurationError(
                "OPENAI_MODEL is not configured."
            )

        if timeout_seconds <= 0:
            raise OpenAIConfigurationError(
                "OPENAI_TIMEOUT_SECONDS must be positive."
            )

        normalized_reasoning_effort = (
            reasoning_effort.strip()
            if reasoning_effort is not None
            else None
        )

        if (
            reasoning_effort is not None
            and not normalized_reasoning_effort
        ):
            raise OpenAIConfigurationError(
                "OpenAI reasoning effort must not be empty."
            )

        if (
            max_output_tokens is not None
            and max_output_tokens <= 0
        ):
            raise OpenAIConfigurationError(
                "OpenAI max output tokens must be positive."
            )

        self.api_key = normalized_api_key
        self.model = normalized_model
        self.timeout_seconds = timeout_seconds
        self.reasoning_effort = (
            normalized_reasoning_effort
        )
        self.max_output_tokens = max_output_tokens

    def generate(
        self,
        instructions: str,
        input_text: str,
        text_format: dict[str, Any] | None = None,
    ) -> GeneratedText:
        """
        Generate one text response.

        `text_format` requests the Responses API's native structured-
        output mode (a JSON Schema the model is constrained to conform
        to) - passed through as-is as the request's "text.format"
        field. Callers that don't need it (answer generation, rerank)
        simply omit it, unaffected.
        """

        request_body = {
            "model": self.model,
            "instructions": instructions,
            "input": input_text,
            "store": False,
        }

        if self.reasoning_effort is not None:
            request_body["reasoning"] = {
                "effort": self.reasoning_effort,
            }

        if self.max_output_tokens is not None:
            request_body["max_output_tokens"] = (
                self.max_output_tokens
            )

        if text_format is not None:
            request_body["text"] = {
                "format": text_format,
            }

        encoded_body = json.dumps(
            request_body
        ).encode(
            "utf-8"
        )

        request = Request(
            url=OPENAI_RESPONSES_URL,
            data=encoded_body,
            method="POST",
            headers={
                "Authorization": (
                    f"Bearer {self.api_key}"
                ),
                "Content-Type": "application/json",
            },
        )

        try:
            with urlopen(
                request,
                timeout=self.timeout_seconds,
            ) as response:
                raw_response = response.read()

        except HTTPError as error:
            error_message = (
                f"OpenAI returned HTTP {error.code}."
            )

            try:
                error_payload = json.loads(
                    error.read().decode(
                        "utf-8"
                    )
                )

                api_error = error_payload.get(
                    "error",
                    {},
                )

                if isinstance(
                    api_error,
                    dict,
                ):
                    api_message = api_error.get(
                        "message"
                    )

                    if isinstance(
                        api_message,
                        str,
                    ) and api_message.strip():
                        error_message = api_message.strip()

            except (
                JSONDecodeError,
                UnicodeDecodeError,
            ):
                pass

            raise OpenAIResponseError(
                error_message,
                retryable=error.code in (429, 500, 502, 503, 504),
                status_code=error.code,
            ) from error

        except (
            URLError,
            TimeoutError,
            OSError,
        ) as error:
            raise OpenAIResponseError(
                "OpenAI could not be reached.",
                retryable=True,
            ) from error

        try:
            payload = json.loads(
                raw_response.decode(
                    "utf-8"
                )
            )

        except (
            JSONDecodeError,
            UnicodeDecodeError,
        ) as error:
            raise OpenAIResponseError(
                "OpenAI returned invalid JSON."
            ) from error

        if not isinstance(
            payload,
            dict,
        ):
            raise OpenAIResponseError(
                "OpenAI returned an invalid response."
            )

        if payload.get("status") == "incomplete":
            incomplete_details = payload.get(
                "incomplete_details",
                {},
            )

            reason = (
                incomplete_details.get("reason")
                if isinstance(
                    incomplete_details,
                    dict,
                )
                else None
            )

            if not isinstance(reason, str):
                reason = "unknown reason"

            raise OpenAIResponseError(
                "OpenAI returned an incomplete response: "
                f"{reason}."
            )

        response_model = payload.get(
            "model",
            self.model,
        )

        if not isinstance(
            response_model,
            str,
        ):
            response_model = self.model

        return GeneratedText(
            text=_extract_output_text(
                payload
            ),
            model=response_model,
        )


def _get_configured_openai_client(
    reasoning_effort: str,
    max_output_tokens: int,
) -> OpenAIResponsesClient:
    """Build an OpenAI client with an explicit reasoning/token budget."""

    settings = get_settings()

    if not settings.openai_api_key:
        raise OpenAIConfigurationError(
            "OPENAI_API_KEY is not configured."
        )

    return OpenAIResponsesClient(
        api_key=settings.openai_api_key,
        model=settings.openai_model,
        timeout_seconds=(
            settings.openai_timeout_seconds
        ),
        reasoning_effort=reasoning_effort,
        max_output_tokens=max_output_tokens,
    )


def get_openai_answer_client() -> OpenAIResponsesClient:
    """Build the OpenAI client used for grounded answer generation."""

    settings = get_settings()

    return _get_configured_openai_client(
        reasoning_effort=(
            settings.openai_answer_reasoning_effort
        ),
        max_output_tokens=(
            settings.openai_answer_max_output_tokens
        ),
    )


def get_openai_rerank_client() -> OpenAIResponsesClient:
    """Build the OpenAI client used for search-result reranking."""

    settings = get_settings()

    return _get_configured_openai_client(
        reasoning_effort=(
            settings.openai_rerank_reasoning_effort
        ),
        max_output_tokens=(
            settings.openai_rerank_max_output_tokens
        ),
    )


def get_openai_understanding_client() -> OpenAIResponsesClient:
    """Build the OpenAI client used for semantic request understanding."""

    settings = get_settings()

    return _get_configured_openai_client(
        reasoning_effort=(
            settings.openai_understanding_reasoning_effort
        ),
        max_output_tokens=(
            settings.openai_understanding_max_output_tokens
        ),
    )